server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://140.143.19.42:3306/ar_album
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true